apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: "{{ .Values.general.name }}-github-trigger"
  namespace: {{.Release.Namespace}}
spec:
  interceptors:
    - ref:
        name: cel
      params:
        - name: overlays
          value:
            - key: branchName
              expression: "body.ref.split('/')[2]"
        - name: filter
          value: >
            body.ref.split('/')[2] == 'main' &&
            body.head_commit.modified.exists(file,
              file.startsWith('social-middleware') || file.startsWith('social-middleware-helm') || file.startsWith('pipelines-middleware-helm')
            )
    - ref:
        name: github
        kind: ClusterInterceptor
      params:
        - name: eventTypes
          value:
            - pull_request
            - push
        - name: secretRef
          value:
            secretName: "{{ .Values.general.name }}-github-webhook-secret"
            secretKey: webhook-token
  bindings:
    - ref: "{{ .Values.general.name }}-github-trigger-binding"
  template:
    ref: "{{ .Values.general.name }}-github-trigger"