{{- if hasSuffix "-prod" .Release.Namespace }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.mongodb.podlabel }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.mongodb.podlabel }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{ .Values.mongodb.podlabel }}
{{- end }}
