apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      {{- if hasSuffix "-prod" .Release.Namespace }}
      storage: {{ .Values.mongodb.prod.storage.size }}
      {{- else }}
      storage: {{ .Values.mongodb.dev.storage.size }}
      {{- end }}
