apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongodb.podlabel }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.mongodb.podlabel }}
spec:
  selector:
    app: {{ .Values.mongodb.podlabel }}
  ports:
    - name: mongo
      protocol: TCP
      port: {{ .Values.mongodb.port }}
      targetPort: {{ .Values.mongodb.targetport }}
  type: ClusterIP