apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongodb.podlabel }}
  namespace: {{ .Release.Namespace }}
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: mongodb-tls
  labels:
    app: {{ .Values.mongodb.podlabel }}
spec:
  selector:
    app: {{ .Values.mongodb.podlabel }}
  ports:
    - name: mongo
      protocol: TCP
      port: {{ .Values.mongodb.port }}
      targetPort: {{ .Values.mongodb.targetport }}
  {{- if hasSuffix "-prod" .Release.Namespace }}
  clusterIP: None
  {{- else }}
  type: ClusterIP
  {{- end }}
