apiVersion: v1
kind: Pod
metadata:
  name: mongodb-test-client
  namespace: {{ .Release.Namespace }}
  labels:
    app: mongodb-test-client
spec:
  containers:
    - name: mongo-client
      image: {{ .Values.mongodb.image }}
      command:
        - sleep
        - "3600"
      env:
        - name: MONGODB_USER
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: database-user
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: database-password
        - name: MONGO_INITDB_DATABASE
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: database-name
        - name: MONGODB_SERVICE
          value: "{{ .Values.mongodb.podlabel }}"
        - name: MONGODB_PORT
          value: "{{ .Values.mongodb.port }}"
      volumeMounts:
        - name: mongodb-ca
          mountPath: /etc/mongodb-ca
          readOnly: true
  volumes:
    - name: mongodb-ca
      configMap:
        name: mongodb-ca-bundle
  restartPolicy: Never
