apiVersion: batch/v1
kind: Job
metadata:
  name: mongodb-verify-users-{{ .Release.Revision }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: mongodb-verify-users
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    # DISABLED: User initialization is now handled by the MongoDB pod itself
    # This job can be manually created for verification purposes
    # helm.sh/hook: post-install,post-upgrade
    # helm.sh/hook-weight: "5"
    # helm.sh/hook-delete-policy: before-hook-creation
    # "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: mongodb-init-user
    spec:
      restartPolicy: Never
      containers:
        - name: init-user
          image: {{ .Values.mongodb.image }}
          command:
            - /bin/sh
            - -c
            - |
              echo "=== MongoDB User Verification Job ==="
              echo "NOTE: This job only verifies users exist. User creation is handled by the MongoDB pod."
              echo ""
              echo "Waiting for MongoDB to be ready..."

              # Wait for MongoDB to be ready (max 60 seconds)
              COUNTER=0
              MAX_TRIES=60

              while [ $COUNTER -lt $MAX_TRIES ]; do
                echo "Attempt $((COUNTER + 1))/$MAX_TRIES: Checking MongoDB connection..."

                if mongosh "mongodb://$MONGODB_USER:$MONGODB_PASSWORD@$MONGODB_SERVICE:$MONGODB_PORT/$MONGO_INITDB_DATABASE?tls=true&tlsAllowInvalidCertificates=true" \
                  --quiet \
                  --eval "db.adminCommand('ping')" > /dev/null 2>&1; then
                  echo "SUCCESS: MongoDB is ready and authentication works!"
                  break
                fi

                COUNTER=$((COUNTER + 1))
                if [ $COUNTER -eq $MAX_TRIES ]; then
                  echo "ERROR: Could not connect to MongoDB after $MAX_TRIES attempts"
                  exit 1
                fi

                sleep 2
              done

              echo ""
              echo "=== Verifying MongoDB Users ==="

              # Verify application user exists and has correct roles
              mongosh "mongodb://$MONGODB_USER:$MONGODB_PASSWORD@$MONGODB_SERVICE:$MONGODB_PORT/$MONGO_INITDB_DATABASE?tls=true&tlsAllowInvalidCertificates=true" \
                --quiet \
                --eval "
                  print('Checking application user: $MONGODB_USER');
                  const user = db.getUser('$MONGODB_USER');

                  if (!user) {
                    print('ERROR: User does not exist');
                    quit(1);
                  }

                  print('SUCCESS: User exists');
                  print('Database: $MONGO_INITDB_DATABASE');
                  print('Roles: ' + JSON.stringify(user.roles));

                  // Test connection status
                  const status = db.runCommand({connectionStatus: 1});
                  print('Authenticated as: ' + JSON.stringify(status.authInfo.authenticatedUsers));
                "

              if [ $? -eq 0 ]; then
                echo ""
                echo "=== Verification Complete - All Users Configured Correctly ==="
              else
                echo "ERROR: Verification failed"
                exit 1
              fi
          env:
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: database-user
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: database-password
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: database-name
            - name: MONGODB_SERVICE
              value: "{{ .Values.mongodb.podlabel }}"
            - name: MONGODB_PORT
              value: "{{ .Values.mongodb.port }}"
