{{- if or (hasSuffix "-prod" .Release.Namespace) (hasSuffix "-test" .Release.Namespace) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-backup
  namespace: {{ .Release.Namespace }}
  labels:
    app: mongodb
    component: backup
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: netapp-file-backup
  resources:
    requests:
      {{- if hasSuffix "-prod" .Release.Namespace }}
      storage: 3Gi
      {{- else }}
      storage: 2Gi
      {{- end }}
{{- end }}
