apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-nextjs-to-mongodb
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: mongodb
  ingress:
    - ports:
        - protocol: TCP
          port: {{ .Values.mongodb.port | default 27017 }}
      from:
        - podSelector:
            matchLabels:
              app: {{ .Values.nextjs.podLabel | default "nextjs-app" }}
  policyTypes:
    - Ingress