apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nextjs.podlabel }}
  namespace: {{ .Release.Namespace }}
spec:
  type:  "ClusterIP" 
  selector:
    app: {{ .Values.nextjs.podlabel | default "social-middleware" }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.nextjsservice.port | default 80 }}
      targetPort: {{ .Values.nextjsservice.targetPort | default 3000 }}
  internalTrafficPolicy: "Cluster"
  sessionAffinity: None