kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-traffic-from-gateway-to-api
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: caregiver-portal
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              environment: test
              name: b8840c
    - from:
        - namespaceSelector:
            matchLabels:
              environment: prod
              name: b8840c
  policyTypes:
    - Ingress
