kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  annotations:
    name: mongodb
    namespace: {{ .Release.Namespace }}
  labels:
    app: mongodb
    app.kubernetes.io/managed-by: Helm
spec:
  podSelector:
    matchLabels:
      app: mongodb
  ingress:
    - ports:
        - protocol: TCP
          port: 27017
      from:
        - podSelector:
            matchLabels:
              app: social-middleware
    - ports:
        - protocol: TCP
          port: 27017
      from:
        - podSelector:
            matchLabels:
              app: mongodb-init-user
    - ports:
        - protocol: TCP
          port: 27017
      from:
        - podSelector:
            matchLabels:
              app: mongodb-test-client
  policyTypes:
    - Ingress
