apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app.openshift.io/runtime: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7.2
          ports:
            - containerPort: 6379
          args: ["--appendonly", "yes"]
          env:
            - name: REDIS_HOST
              value: "localhost"
            - name: REDIS_PORT
              value: "6379"
            - name: QUEUE_JOB_ATTEMPTS
              value: "3"
            - name: QUEUE_BACKOFF_DELAY
              value: "5000"
          volumeMounts:
            - name: redis-storage
              mountPath: /data
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: redis-pvc