apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-deployer-binding
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: f6e00d-tools
roleRef:
  kind: Role
  name: pipeline-deployer
  apiGroup: rbac.authorization.k8s.io
