apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: generate-id
  namespace: {{ .Release.Namespace }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  results:
    - name: short-commit
      description: The short commit SHA that was fetched by this Task
      type: string
    - name: build-uid
      description: Unique build identifier
      type: string
  steps:
    - name: generate
      image: alpine/git:latest
      script: |
        #!/bin/sh

        # Get short commit
        SHORT_SHA=$(git rev-parse --short HEAD)
        echo -n "$SHORT_SHA" > $(results.short-commit.path)

        # Generate unique UID
        BUILD_UID=$(printf '%s ' "$(date)" | cksum | cut -f1 -d ' ')
        echo -n "$BUILD_UID" > $(results.build-uid.path)

        echo "Generated ID $SHORT_SHA-$BUILD_UID"
      workingDir: $(workspaces.source.path)
      computeResources: {}
  workspaces:
    - name: source