apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: reroll-deployment
  namespace: {{.Release.Namespace}}
spec:
  description: |
    This task will re-roll a single deployment using OpenShift's `oc rollout restart` command.
  params:
    - name: deploymentName
      description: The name of the deployment to be re-rolled.
      type: string
    - name: namespace
      description: The namespace where the deployment exists.
      type: string
  steps:
    - name: reroll-deployment
      image: 'openshift/origin-cli:latest' 
      script: |
        #!/bin/bash
        echo "Re-rolling deployment: $(params.deploymentName) in namespace: $(params.namespace)"
        
        # Perform the rollout restart
        oc rollout restart deployment/$(params.deploymentName) -n $(params.namespace)