apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eventlistener-pipelinerun-creator-binding
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: eventlistener-pipelinerun-creator
