apiVersion: v1
kind: ConfigMap
metadata:
  name: apisix-config-template
  namespace: {{ .Release.Namespace }}
data:
  config-template.yaml: |
    apisix:
      node_listen: 9080
      enable_admin: true
      admin_key:
        - name: "admin"
          key: "__ADMIN_KEY__"
          role: admin

    deployment:
      role: data_plane
      role_data_plane:
        config_provider: yaml

    routes:
      - uri: /*
        name: "vite-app"
        upstream:
          type: roundrobin
          nodes:
            "vite-app.f6e00d-tools.svc.cluster.local:80": 1