apiVersion: apps/v1
kind: Deployment
metadata:
  name: apisix
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apisix
  template:
    metadata:
      labels:
        app: apisix
    spec:
      volumes:
        - name: apisix-conf
          emptyDir: {}
        - name: admin-key
          secret:
            secretName: apisix-admin-key
        - name: config-template
          configMap:
            name: apisix-config-template

      initContainers:
        - name: init-config
          image: registry.access.redhat.com/ubi9/ubi-minimal
          command: ["/bin/sh", "-c"]
          args:
            - |
              mkdir -p /var/apisix/conf
              cp /etc/template/config-template.yaml /var/apisix/conf/config.yaml
              sed -i "s|__ADMIN_KEY__|$(cat /etc/secrets/admin_key | sed 's/[&/\]/\\&/g')|" /var/apisix/conf/config.yaml
          volumeMounts:
            - name: apisix-conf
              mountPath: /var/apisix/conf
            - name: admin-key
              mountPath: /etc/secrets
              readOnly: true
            - name: config-template
              mountPath: /etc/template
              readOnly: true

      containers:
        - name: apisix
          image: image-registry.openshift-image-registry.svc:5000/f6e00d-tools/apisix
          ports:
            - name: http
              containerPort: 9080
            - name: https
              containerPort: 9443
          volumeMounts:
            - name: apisix-conf
              mountPath: /var/apisix/conf
