apiVersion: v1
kind: Service
metadata:
  name: apisix
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: apisix
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 9443